name: Continuous Integration
on: [push]

jobs:
    install:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 13.x
              uses: actions/setup-node@v1
              with:
                  node-version: '13.x'

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install NPM dependencies
              run: npm install

    build:
        name: Build js bundle
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 13.x
              uses: actions/setup-node@v1
              with:
                  node-version: '13.x'

            - name: Restore cached node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Run Rollup build
              run: npm run build

    lint:
        name: Run linter
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 13.x
              uses: actions/setup-node@v1
              with:
                  node-version: '13.x'

            - name: Restore cached node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Run Eslint
              run: npm run lint

    test:
        name: Run tests
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 13.x
              uses: actions/setup-node@v1
              with:
                  node-version: '13.x'

            - name: Restore cached node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Run Jest
              run: npm run test

    prettier:
        name: Run prettier
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 13.x
              uses: actions/setup-node@v1
              with:
                  node-version: '13.x'

            - name: Restore cached node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Run Prettier
              run: npm run prettier:check

    type-check:
        name: Run TSC type check
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 13.x
              uses: actions/setup-node@v1
              with:
                  node-version: '13.x'

            - name: Restore cached node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Run TSC
              run: npm run type-check
